sites:
  istanbul:
    hypervisors:
      - type: vmware
        host: ivcenter01.fatihsolen.local
        username: "vmware_user"
        password: "vmware_pass"
      - type: vmware
        host: ivcenter02.fatihsolen.local
        username: "vmware_user"
        password: "vmware_pass"
      - type: harvester # KubeVirt
        host: iharvester01.fatihsolen.local
        api_url: "https://iharvester01.fatihsolen.local"
        api_token: "harvester_token"
      - type: harvester # KubeVirt
        host: iharvester02.fatihsolen.local
        api_url: "https://iharvester02.fatihsolen.local"
        api_token: "harvester_token"
      - type: cloudstack
        host: icloudstack01.fatihsolen.local/client/api
        api_url: "https://icloudstack01.fatihsolen.local/client/api"
        api_key: "cloudstack_api_key"
        secret_key: "cloudstack_secret_key"
      - type: cloudstack
        host: icloudstack02.fatihsolen.local/client/api
        api_url: "https://icloudstack02.fatihsolen.local/client/api"
        api_key: "cloudstack_api_key"
        secret_key: "cloudstack_secret_key"
    storage:
      - type: purefa
        host: ipurefa01.fatihsolen.local
        api_url: "https://ipurefa01.fatihsolen.local"
        api_token: "purefa_api_token"
      - type: purefa
        host: ipurefa02.fatihsolen.local
        api_url: "https://ipurefa02.fatihsolen.local"
        api_token: "purefa_api_token"
    dns:
      - type: msdns
        host: msdns.fatihsolen.local
        username: "dns_user"
        password: "dns_pass"
    ipam:
      - type: phpipam
        host: iipam.fatihsolen.local
        base_url: "https://iipam.fatihsolen.local"
        app_id: "phpipam_app_id"
        username: "phpipam_user"
        password: "phpipam_pass"
    vault:
      - type: openboa
        host: vault.fatihsolen.local
  ankara:
    hypervisors:
      - type: vmware
        host: avcenter01.fatihsolen.local
        username: "vmware_user"
        password: "vmware_pass"
      - type: vmware
        host: avcenter02.fatihsolen.local
        username: "vmware_user"
        password: "vmware_pass"
      - type: harvester # KubeVirt
        host: aharvester01.fatihsolen.local
        api_url: "https://aharvester01.fatihsolen.local"
        api_token: "harvester_token"
      - type: harvester # KubeVirt
        host: aharvester02.fatihsolen.local
        api_url: "https://aharvester02.fatihsolen.local"
        api_token: "harvester_token"
      - type: cloudstack
        host: acloudstack01.fatihsolen.local/client/api
        api_url: "https://acloudstack01.fatihsolen.local/client/api"
        api_key: "cloudstack_api_key"
        secret_key: "cloudstack_secret_key"
      - type: cloudstack
        host: acloudstack02.fatihsolen.local/client/api
        api_url: "https://acloudstack02.fatihsolen.local/client/api"
        api_key: "cloudstack_api_key"
        secret_key: "cloudstack_secret_key"
    storage:
      - type: purefa
        host: apurefa01.fatihsolen.local
        api_url: "https://apurefa01.fatihsolen.local"
        api_token: "purefa_api_token"
      - type: purefa
        host: apurefa02.fatihsolen.local
        api_url: "https://apurefa02.fatihsolen.local"
        api_token: "purefa_api_token"
    dns:
      - type: msdns
        host: msdns.fatihsolen.local
        username: "dns_user"
        password: "dns_pass"
    ipam:
      - type: phpipam
        host: aipam.fatihsolen.local
        base_url: "https://aipam.fatihsolen.local"
        app_id: "phpipam_app_id"
        username: "phpipam_user"
        password: "phpipam_pass"
    vault:
      - type: openboa
        host: vault.fatihsolen.local
